services:
  db:
    container_name: rails_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rails:
    container_name: rails_api
    build:
      context: ./railsapp
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    volumes:
      - ./railsapp:/app
    working_dir: /app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/development
      RAILS_ENV: development
    depends_on:
      - db
    ports:
      - "3000:3000"

  react:
    container_name: react_frontend
    build:
      context: ./reactapp
    command: bun run dev -- --host
    volumes:
      - ./reactapp:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    working_dir: /app
    environment:
      - NODE_ENV=development

  nginx:
    container_name: nginx_proxy
    image: nginx
    depends_on:
      - rails
      - react
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data: